### ISSUE TITLE
API useEslintRc is not working?

### ISSUE THREAD

**Issue by Emiya0306** [arackaf/customize-cra#198] opened 2019-12-13 10:01 UTC
### Description:
Just like this configuration below, the .eslintrc is not working. Is anything wrong?

### Pictures:
![image](https://user-images.githubusercontent.com/12878132/70791365-f4c2d100-1dd1-11ea-8996-c50c98b4abfb.png)
![image](https://user-images.githubusercontent.com/12878132/70791402-06a47400-1dd2-11ea-960b-005db06189d4.png)
![image](https://user-images.githubusercontent.com/12878132/70791435-158b2680-1dd2-11ea-9389-1e6d0b141d2b.png)

### Result:
![image](https://user-images.githubusercontent.com/12878132/70791545-44a19800-1dd2-11ea-9a74-b294ab228c4b.png)

**Comment by with-heart** [comment] 2019-12-15 03:56
Closing as a duplicate of #175 

Feel free to post this example there!

**Closed by with-heart** 2019-12-15 03:56 UTC
Labels: duplicate

**Comment by Emiya0306** [comment] 2019-12-16 02:05
@with-heart 
I see we can use `EXTEND_ESLINT=true` and add `eslintConfig` in package.json, but that does not resolve that I would like to use `useEslintRc`.
I like `useEslintRc` because I can modify the .eslintrc file location.
Will this be improved in the next version?
