### ISSUE TITLE
addWebpackModuleRule helphelpme

### ISSUE THREAD

**Issue by deng302949** [arackaf/customize-cra#162] opened 2019-09-11 03:37 UTC
addWebpackModuleRule(
    {
      test: /\.worker\.js$/,
      use: 'worker-loader'
    }
  ),
error: e.use.some is not a function.
"customize-cra": "^0.6.0",

**Comment by with-heart** [comment] 2019-09-11 16:35
Duplicate of #153

**Closed by with-heart** 2019-09-11 16:35 UTC
Labels: duplicate
